<?php

declare(strict_types=1);

return [
    'title' => 'Invoices',
    'subtitle' => 'Tax invoices issued after a payment is confirmed.',
    'no_invoices' => 'No invoices yet.',
    'download' => 'Download PDF',
    'pending' => 'Issued once payment is confirmed.',
    'issued_total' => 'Issued total',

    'filter_source' => 'Source',
    'all_sources' => 'All sources',
    'search' => 'Search by number',
    'search_placeholder' => 'INV-…',

    'sources' => [
        'order' => 'Store order',
        'subscription' => 'Subscription',
    ],

    'fields' => [
        'number' => 'Invoice number',
        'customer' => 'Customer',
        'source' => 'Source',
        'issued_at' => 'Issued',
        'total' => 'Total',
        'reference' => 'Related to',
    ],

    'card' => [
        'title' => 'Invoice',
    ],

    'mail' => [
        'subject' => 'Your invoice :number',
        'greeting' => 'Hello,',
        'intro' => 'Your invoice :number for :total SAR is ready.',
        'attached' => 'The PDF is attached to this email.',
        'action' => 'Download invoice',
    ],

    'pdf' => [
        'title' => 'Tax Invoice',
        'number' => 'Invoice no.',
        'issued_at' => 'Issue date',
        'seller' => 'Seller',
        'buyer' => 'Buyer',
        'vat_number' => 'VAT number',
        'description' => 'Description',
        'quantity' => 'Qty',
        'unit_price' => 'Unit price',
        'line_total' => 'Amount',
        'lines_total' => 'Lines total',
        'discount' => 'Discount',
        'net' => 'Taxable amount',
        'tax' => 'VAT (:rate%)',
        'total' => 'Total',
        'currency' => 'SAR',
        'qr_hint' => 'ZATCA QR',
        'reference' => 'Reference #:reference',
        'generated' => 'Generated by New Me',
        'delivery_line' => 'Delivery fee',
        'subscription_line' => ':plan — :days delivery days',
    ],
];
