<?php

declare(strict_types=1);

/**
 * Structural store catalog (locale-agnostic).
 * Product names / category labels live in lang/website.php under store.products / store.sub_labels.
 */
return [
    'total' => 48,
    'counts' => [
        'all' => 48,
        'bakery' => 29,
        'sweets' => 16,
        'others' => 3,
    ],
    'products' => [
        [
            'id' => 'breadcrumbs_plain',
            'cat' => 'bakery',
            'sub' => 'crumbs',
            'href' => 'https://newmeforever.com/en/shop/breadcrumbs-583',
            'img' => 'p121_560x580.jpg',
            'kcal' => 105,
            'serving' => 'per_30g',
            'protein' => '3',
            'fat' => '1',
            'carbs' => '20',
            'note' => 'est',
            'price' => '15',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'breadcrumbs_italian',
            'cat' => 'bakery',
            'sub' => 'crumbs',
            'href' => 'https://newmeforever.com/en/shop/italian-seasoning-breadcrumbs-498',
            'img' => 'p122_560x580.jpg',
            'kcal' => 45,
            'serving' => 'per_serving',
            'protein' => '1.5',
            'fat' => '0.5',
            'carbs' => '8',
            'note' => 'real',
            'price' => '15',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'breadcrumbs_garlic',
            'cat' => 'bakery',
            'sub' => 'crumbs',
            'href' => 'https://newmeforever.com/en/shop/garlic-breadcrumbs-497',
            'img' => 'p123_560x580.jpg',
            'kcal' => 48,
            'serving' => 'per_30g',
            'protein' => '1.5',
            'fat' => '0.6',
            'carbs' => '8',
            'note' => 'est',
            'price' => '15',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'rusk_zaatar',
            'cat' => 'bakery',
            'sub' => 'rusk',
            'href' => 'https://newmeforever.com/en/shop/za-atar-rusk-495',
            'img' => 'p124_560x580.jpg',
            'kcal' => 90,
            'serving' => 'per_2_pieces',
            'protein' => '3',
            'fat' => '3',
            'carbs' => '13',
            'note' => 'est',
            'price' => '9',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'rusk_sweet',
            'cat' => 'bakery',
            'sub' => 'rusk',
            'href' => 'https://newmeforever.com/en/shop/sweet-rusk-494',
            'img' => 'p125_560x580.jpg',
            'kcal' => 100,
            'serving' => 'per_2_pieces',
            'protein' => '2.5',
            'fat' => '3',
            'carbs' => '16',
            'note' => 'est',
            'price' => '9',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'rusk_salted',
            'cat' => 'bakery',
            'sub' => 'rusk',
            'href' => 'https://newmeforever.com/en/shop/salted-rusk-493',
            'img' => 'p126_560x580.jpg',
            'kcal' => 88,
            'serving' => 'per_2_pieces',
            'protein' => '3',
            'fat' => '3',
            'carbs' => '13',
            'note' => 'est',
            'price' => '9',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'crackers_cheddar',
            'cat' => 'bakery',
            'sub' => 'crackers',
            'href' => 'https://newmeforever.com/en/shop/cheddar-cheese-crackers-492',
            'img' => 'p127_560x580.jpg',
            'kcal' => 140,
            'serving' => 'per_30g',
            'protein' => '4',
            'fat' => '7',
            'carbs' => '15',
            'note' => 'est',
            'price' => '22',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'crackers_zaatar',
            'cat' => 'bakery',
            'sub' => 'crackers',
            'href' => 'https://newmeforever.com/en/shop/za-atar-crackers-491',
            'img' => 'p128_560x580.jpg',
            'kcal' => 130,
            'serving' => 'per_30g',
            'protein' => '3',
            'fat' => '6',
            'carbs' => '16',
            'note' => 'est',
            'price' => '22',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'crackers_rosemary',
            'cat' => 'bakery',
            'sub' => 'crackers',
            'href' => 'https://newmeforever.com/en/shop/rosemary-crackers-490',
            'img' => 'p129_560x580.jpg',
            'kcal' => 130,
            'serving' => 'per_30g',
            'protein' => '3',
            'fat' => '6',
            'carbs' => '16',
            'note' => 'est',
            'price' => '22',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'crackers_seasalt',
            'cat' => 'bakery',
            'sub' => 'crackers',
            'href' => 'https://newmeforever.com/en/shop/sea-salt-crackers-489',
            'img' => 'p130_560x580.jpg',
            'kcal' => 128,
            'serving' => 'per_30g',
            'protein' => '3',
            'fat' => '6',
            'carbs' => '16',
            'note' => 'est',
            'price' => '22',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'crackers_anise',
            'cat' => 'bakery',
            'sub' => 'crackers',
            'href' => 'https://newmeforever.com/en/shop/star-anise-crackers-488',
            'img' => 'p131_560x580.jpg',
            'kcal' => 132,
            'serving' => 'per_30g',
            'protein' => '3',
            'fat' => '6',
            'carbs' => '17',
            'note' => 'est',
            'price' => '22',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'granola_seeds',
            'cat' => 'bakery',
            'sub' => 'crackers',
            'href' => 'https://newmeforever.com/en/shop/granola-seeds-487',
            'img' => 'p132_560x580.jpg',
            'kcal' => 190,
            'serving' => 'per_45g',
            'protein' => '6',
            'fat' => '9',
            'carbs' => '20',
            'note' => 'est',
            'price' => '22',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'croissant_cheese',
            'cat' => 'bakery',
            'sub' => 'croissant',
            'href' => 'https://newmeforever.com/en/shop/cheese-croissant-582',
            'img' => 'p133_560x580.jpg',
            'kcal' => 250,
            'serving' => 'per_piece',
            'protein' => '8',
            'fat' => '13',
            'carbs' => '25',
            'note' => 'est',
            'price' => '11',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'croissant_chocolate',
            'cat' => 'bakery',
            'sub' => 'croissant',
            'href' => 'https://newmeforever.com/en/shop/chocolate-croissant-486',
            'img' => 'p134_560x580.jpg',
            'kcal' => 280,
            'serving' => 'per_piece',
            'protein' => '5',
            'fat' => '15',
            'carbs' => '32',
            'note' => 'est',
            'price' => '16',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'croissant_almond',
            'cat' => 'bakery',
            'sub' => 'croissant',
            'href' => 'https://newmeforever.com/en/shop/almond-croissant-485',
            'img' => 'p135_560x580.jpg',
            'kcal' => 300,
            'serving' => 'per_piece',
            'protein' => '7',
            'fat' => '17',
            'carbs' => '30',
            'note' => 'est',
            'price' => '19',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'croissant_plain',
            'cat' => 'bakery',
            'sub' => 'croissant',
            'href' => 'https://newmeforever.com/en/shop/plain-croissant-482',
            'img' => 'p136_560x580.jpg',
            'kcal' => 230,
            'serving' => 'per_piece',
            'protein' => '5',
            'fat' => '12',
            'carbs' => '26',
            'note' => 'est',
            'price' => '10',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'pie_zaatar',
            'cat' => 'bakery',
            'sub' => 'pies',
            'href' => 'https://newmeforever.com/en/shop/za-atar-pie-484',
            'img' => 'p137_560x580.jpg',
            'kcal' => 180,
            'serving' => 'per_piece',
            'protein' => '4',
            'fat' => '8',
            'carbs' => '23',
            'note' => 'est',
            'price' => '10',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'pizza',
            'cat' => 'bakery',
            'sub' => 'pies',
            'href' => 'https://newmeforever.com/en/shop/pizza-481',
            'img' => 'p138_560x580.jpg',
            'kcal' => 220,
            'serving' => 'per_piece',
            'protein' => '9',
            'fat' => '8',
            'carbs' => '27',
            'note' => 'est',
            'price' => '10',
            'flag' => 'sale',
            'feat' => false,
        ],
        [
            'id' => 'pie_spinach',
            'cat' => 'bakery',
            'sub' => 'pies',
            'href' => 'https://newmeforever.com/en/shop/spinach-pie-480',
            'img' => 'p139_560x580.jpg',
            'kcal' => 170,
            'serving' => 'per_piece',
            'protein' => '5',
            'fat' => '7',
            'carbs' => '21',
            'note' => 'est',
            'price' => '10',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'pie_cheese',
            'cat' => 'bakery',
            'sub' => 'pies',
            'href' => 'https://newmeforever.com/en/shop/cheese-pie-478',
            'img' => 'p140_560x580.jpg',
            'kcal' => 200,
            'serving' => 'per_piece',
            'protein' => '8',
            'fat' => '9',
            'carbs' => '22',
            'note' => 'est',
            'price' => '10',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'bread_eid',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => 'https://newmeforever.com/en/shop/eid-bread-477',
            'img' => 'p141_560x580.jpg',
            'kcal' => 210,
            'serving' => 'per_piece',
            'protein' => '7',
            'fat' => '3',
            'carbs' => '38',
            'note' => 'est',
            'price' => '23',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'bread_multiseed',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => '/product',
            'img' => 'p142_560x580.jpg',
            'kcal' => 119,
            'serving' => 'per_piece',
            'protein' => '12.1',
            'fat' => '4',
            'carbs' => '5',
            'note' => 'real',
            'price' => '23',
            'flag' => 'bestseller',
            'feat' => true,
        ],
        [
            'id' => 'bread_simit',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => 'https://newmeforever.com/en/shop/simit-bread-475',
            'img' => 'p143_560x580.jpg',
            'kcal' => 230,
            'serving' => 'per_piece',
            'protein' => '8',
            'fat' => '4',
            'carbs' => '42',
            'note' => 'est',
            'price' => '23',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'bread_filo',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => 'https://newmeforever.com/en/shop/filo-sheets-474',
            'img' => 'p144_560x580.jpg',
            'kcal' => 60,
            'serving' => 'per_slice',
            'protein' => '2',
            'fat' => '0.5',
            'carbs' => '12',
            'note' => 'est',
            'price' => '22',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'bread_baguette',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => 'https://newmeforever.com/en/shop/baguette-473',
            'img' => 'p145_560x580.jpg',
            'kcal' => 180,
            'serving' => 'per_half',
            'protein' => '7',
            'fat' => '1',
            'carbs' => '36',
            'note' => 'est',
            'price' => '11.99',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'bread_burger',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => 'https://newmeforever.com/en/shop/burger-bun-472',
            'img' => 'p146_560x580.jpg',
            'kcal' => 170,
            'serving' => 'per_piece',
            'protein' => '6',
            'fat' => '3',
            'carbs' => '30',
            'note' => 'est',
            'price' => '11.99',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'bread_toast',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => 'https://newmeforever.com/en/shop/toast-471',
            'img' => 'p147_560x580.jpg',
            'kcal' => 85,
            'serving' => 'per_slice',
            'protein' => '3.5',
            'fat' => '1',
            'carbs' => '15',
            'note' => 'est',
            'price' => '11.99',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'bread_samoli',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => 'https://newmeforever.com/en/shop/samoli-bread-470',
            'img' => 'p148_560x580.jpg',
            'kcal' => 160,
            'serving' => 'per_piece',
            'protein' => '5',
            'fat' => '2',
            'carbs' => '30',
            'note' => 'est',
            'price' => '11.99',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'bread_arabic',
            'cat' => 'bakery',
            'sub' => 'bread',
            'href' => 'https://newmeforever.com/en/shop/arabic-bread-469',
            'img' => 'p149_560x580.jpg',
            'kcal' => 140,
            'serving' => 'per_loaf',
            'protein' => '5',
            'fat' => '1',
            'carbs' => '28',
            'note' => 'est',
            'price' => '11.99',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'cake_happy_times',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/happy-times-cake-514',
            'img' => 'p150_560x580.jpg',
            'kcal' => 320,
            'serving' => 'per_slice',
            'protein' => '4',
            'fat' => '14',
            'carbs' => '45',
            'note' => 'est',
            'price' => '200',
            'flag' => 'occasions',
            'feat' => false,
        ],
        [
            'id' => 'cake_marble',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/marble-cake-513',
            'img' => 'p151_560x580.jpg',
            'kcal' => 310,
            'serving' => 'per_slice',
            'protein' => '5',
            'fat' => '14',
            'carbs' => '42',
            'note' => 'est',
            'price' => '49',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'donuts_cinnamon',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/cinnamon-donuts-512',
            'img' => 'p152_560x580.jpg',
            'kcal' => 240,
            'serving' => 'per_piece',
            'protein' => '3',
            'fat' => '11',
            'carbs' => '32',
            'note' => 'est',
            'price' => '30',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'waffle',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/waffle-511',
            'img' => 'p153_560x580.jpg',
            'kcal' => 290,
            'serving' => 'per_piece',
            'protein' => '6',
            'fat' => '12',
            'carbs' => '40',
            'note' => 'est',
            'price' => '30',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'pancake',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/pancake-510',
            'img' => 'p154_560x580.jpg',
            'kcal' => 250,
            'serving' => 'per_piece',
            'protein' => '6',
            'fat' => '8',
            'carbs' => '38',
            'note' => 'est',
            'price' => '30',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'cake_lemon',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/lemon-cake-509',
            'img' => 'p155_560x580.jpg',
            'kcal' => 300,
            'serving' => 'per_slice',
            'protein' => '4',
            'fat' => '13',
            'carbs' => '42',
            'note' => 'est',
            'price' => '33',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'cake_saffron',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/saffron-cake-508',
            'img' => 'p156_560x580.jpg',
            'kcal' => 295,
            'serving' => 'per_slice',
            'protein' => '4',
            'fat' => '12',
            'carbs' => '42',
            'note' => 'est',
            'price' => '33',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'cake_coconut',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/coconut-cake-507',
            'img' => 'p157_560x580.jpg',
            'kcal' => 315,
            'serving' => 'per_slice',
            'protein' => '4',
            'fat' => '16',
            'carbs' => '40',
            'note' => 'est',
            'price' => '33',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'cake_coffee',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/coffee-cake-506',
            'img' => 'p158_560x580.jpg',
            'kcal' => 305,
            'serving' => 'per_slice',
            'protein' => '4',
            'fat' => '13',
            'carbs' => '42',
            'note' => 'est',
            'price' => '33',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'cake_chocolate',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/chocolate-cake-505',
            'img' => 'p159_560x580.jpg',
            'kcal' => 330,
            'serving' => 'per_slice',
            'protein' => '5',
            'fat' => '16',
            'carbs' => '43',
            'note' => 'est',
            'price' => '33',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'mamoul_walnut',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/walnut-mamoul-504',
            'img' => 'p160_560x580.jpg',
            'kcal' => 150,
            'serving' => 'per_piece',
            'protein' => '3',
            'fat' => '7',
            'carbs' => '20',
            'note' => 'est',
            'price' => '20',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'mamoul_pistachio',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/pistachio-mamoul-503',
            'img' => 'p161_560x580.jpg',
            'kcal' => 155,
            'serving' => 'per_piece',
            'protein' => '3',
            'fat' => '7',
            'carbs' => '20',
            'note' => 'est',
            'price' => '20',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'mamoul_date',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/date-mamoul-502',
            'img' => 'p162_560x580.jpg',
            'kcal' => 140,
            'serving' => 'per_piece',
            'protein' => '2',
            'fat' => '5',
            'carbs' => '24',
            'note' => 'est',
            'price' => '16',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'ghoraibah',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/ghoraibah-501',
            'img' => 'p163_560x580.jpg',
            'kcal' => 120,
            'serving' => 'per_piece',
            'protein' => '1.5',
            'fat' => '7',
            'carbs' => '14',
            'note' => 'est',
            'price' => '16',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'cookies_mocha',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/mocha-cookies-500',
            'img' => 'p164_560x580.jpg',
            'kcal' => 110,
            'serving' => 'per_piece',
            'protein' => '1.5',
            'fat' => '5',
            'carbs' => '15',
            'note' => 'est',
            'price' => '15',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'petitfour_chocolate',
            'cat' => 'sweets',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/chocolate-petitfour-499',
            'img' => 'p165_560x580.jpg',
            'kcal' => 95,
            'serving' => 'per_piece',
            'protein' => '1',
            'fat' => '5',
            'carbs' => '12',
            'note' => 'est',
            'price' => '16',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'pickle_white_cabbage',
            'cat' => 'others',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/pickled-white-cabbage-520',
            'img' => 'p166_560x580.jpg',
            'kcal' => 25,
            'serving' => 'per_100g',
            'protein' => '1',
            'fat' => '0.2',
            'carbs' => '4',
            'note' => 'est',
            'price' => '15',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'pickle_red_cabbage',
            'cat' => 'others',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/pickled-red-cabbage-519',
            'img' => 'p167_560x580.jpg',
            'kcal' => 27,
            'serving' => 'per_100g',
            'protein' => '1',
            'fat' => '0.2',
            'carbs' => '5',
            'note' => 'est',
            'price' => '15',
            'flag' => null,
            'feat' => false,
        ],
        [
            'id' => 'pickle_lemons',
            'cat' => 'others',
            'sub' => '',
            'href' => 'https://newmeforever.com/en/shop/pickled-lemons-518',
            'img' => 'p168_560x580.jpg',
            'kcal' => 30,
            'serving' => 'per_100g',
            'protein' => '0.5',
            'fat' => '0.2',
            'carbs' => '7',
            'note' => 'est',
            'price' => '15',
            'flag' => null,
            'feat' => false,
        ],
    ],
];
